# [driver]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [driver]    Script Date: 07.02.2022 13:19:27 ******/
CREATE DATABASE [driver]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'driver', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\driver.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'driver_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\driver_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [driver] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [driver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [driver] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [driver] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [driver] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [driver] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [driver] SET ARITHABORT OFF 
GO
ALTER DATABASE [driver] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [driver] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [driver] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [driver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [driver] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [driver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [driver] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [driver] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [driver] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [driver] SET  DISABLE_BROKER 
GO
ALTER DATABASE [driver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [driver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [driver] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [driver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [driver] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [driver] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [driver] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [driver] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [driver] SET  MULTI_USER 
GO
ALTER DATABASE [driver] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [driver] SET DB_CHAINING OFF 
GO
ALTER DATABASE [driver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [driver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [driver] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [driver] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [driver] SET QUERY_STORE = OFF
GO

# [dbo].[авторизация]

In [0]:
USE [driver]
GO

In [0]:
/****** Object:  Table [dbo].[авторизация]    Script Date: 07.02.2022 13:19:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[авторизация](
	[ID] [nvarchar](50) NULL,
	[Login] [nvarchar](50) NULL,
	[Passwords] [nchar](10) NULL
) ON [PRIMARY]
GO

# [dbo].[карточка водителя]

In [0]:
/****** Object:  Table [dbo].[карточка водителя]    Script Date: 07.02.2022 13:19:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[карточка водителя](
	[ID] [int] NOT NULL,
	[Surname] [nvarchar](50) NULL,
	[Name] [nvarchar](50) NULL,
	[Patronymic] [nvarchar](50) NULL,
	[Passport] [nvarchar](50) NULL,
	[Registration address] [nvarchar](50) NULL,
	[Residential adress] [nvarchar](50) NULL,
	[Place of work] [nvarchar](50) NULL,
	[Position] [nvarchar](50) NULL,
	[Phone] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Photo] [nvarchar](50) NULL,
	[Remarks] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [driver]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [driver] SET  READ_WRITE 
GO